spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy.devdojo: debug

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param #incluir a stacktrace na resposta do servi√ßo tag on_param precisa passar ?trace=true
  tomcat:
    threads:
      max: 20

database:
  url: ${DB_URL:localhost}:${PORT:3306}
  username: ${LOCAL_USERNAME:boozera}
  password: ${LOCAL_PASSWORD:devdojo}